### ISSUE TITLE
key error

### ISSUE THREAD

**Issue by yjg123456** [jiaming-wang/MIP#1]
作者 你好 ，我在运行程序时出现了一下错误
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    solver.run()
  File "/home/gfzx/yjg/image_enhance_Algorithm/MIP-main/solver/solver.py", line 142, in run
    self.save_img(self.sr[0].cpu().data, self.file_name[0])
  File "/home/gfzx/yjg/image_enhance_Algorithm/MIP-main/solver/solver.py", line 90, in save_img
    save_dir=os.path.join('results/',self.cfg['test']['type'])
KeyError: 'test'

我不太清楚代码中的 save_dir=os.path.join('results/',self.cfg['test']['type'])self.cfg中是什么意思，可以讲解一下吗

**Comment by jiaming-wang** [comment]
这个self.cfg是读取的option.yml里面的参数，这个yml中保存的是训练超参数啥的，具体代码可以参考config.py和basesolver.py的代码。
